name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers on push to the main branch
  pull_request:
    branches:
      - main  # Triggers on pull requests to the main branch

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build . --file Dockerfile -t banyumu/action:latest

  push:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Image
      run: docker push banyumu/action:latest

  deploy:
    needs: push
    runs-on: self-hosted
    #runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up SSH key for deployment
      #- name: Set up SSH
      #  uses: webfactory/ssh-agent@v0.5.3
      #  with:
      #    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Copy docker-compose.yml and pull the latest image to your VM
      #- name: Deploy to VM
      #  run: |
      #    ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
      #      docker-compose pull  # Pull the latest images
      #      docker-compose up -d  # Start the containers
      #    EOF
      
      - name: SSH into Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            ssh -o StrictHostKeyChecking=no -i ${{ secrets.SERVER_HOST }}  ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}
            docker compose -f /home/h2o/docker-compose.yml up -d
