name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers on push to the main branch
  pull_request:
    branches:
      - main  # Triggers on pull requests to the main branch

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build . --file Dockerfile -t banyumu/action:latest

  push:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Image
      run: docker push banyumu/action:latest

  deploy:
    needs: push
    #runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: remote docker-compose up via ssh
        uses: appleboy/ssh-action@v0.1.5
        #env:
        #  APPTOKEN: ${‎{ secrets.GITHUB_TOKEN }‎}
        #  USERNAME: ${‎{ secrets.DEPLOY_USERNAME }‎}
        with:
          host: ${‎{ secrets.DEPLOY_HOST }‎}
          username: ${‎{ secrets.DEPLOY_USERNAME }‎}
          key: ${‎{ secrets.DEPLOY_KEY }‎}
          port: 22
          envs: APPTOKEN,USERNAME
          script: |
            cd ~ && docker compose -f docker-compose.yml
