name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers on push to the main branch
  pull_request:
    branches:
      - main  # Triggers on pull requests to the main branch

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    #steps:
    #- name: Checkout Code
     # uses: actions/checkout@v3

    #- name: Set up Node.js
     # uses: actions/setup-node@v3
     # with:
     #   node-version: '16'  # Use the desired Node.js version

    #- name: Install Dependencies
     # run: npm install

    #- name: Run Tests
    #  run: npm test
    steps:
    - name: Build Docker Image
      run: docker build -t banyumu/gihub-action:latest .

  push:
    needs: build
    runs-on: self-hosted
    #runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    #- name: Push Docker Image
    #  run: docker push your-dockerhub-username/your-app-name:latest

  deploy:
    needs: push
    runs-on: self-hosted
    #runs-on: ubuntu-latest

    steps:
    - name: SSH into Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull your-dockerhub-username/your-app-name:latest
          docker-compose up -d --no-deps your-service-name
